---
- block:
  - name: Get the latest version of direnv
    shell: curl https://api.github.com/repos/direnv/direnv/releases/latest | jq .tag_name -r | sed "s/\"//g"
    register: direnv_version

  - name: Get direnv
    become: yes
    get_url:
      url: https://github.com/direnv/direnv/releases/download/{{ direnv_version.stdout }}/direnv.linux-amd64
      dest: /usr/local/bin/direnv

  - name: Apply executable permissions to the direnv
    become: yes
    file:
      path: /usr/local/bin/direnv
      mode: "a+x"
