---
- block:
  - name: download source
    get_url:
      url: https://github.com/git/git/archive/v2.16.2.tar.gz
      dest: /tmp

  - name: unarchive
    command: chdir=/tmp tar zxvf git-2.16.2.tar.gz

  - name: make
    become: yes
    command: chdir=/tmp/git-2.16.2 make prefix=/usr/local all

  - name: install
    become: yes
    command: chdir=/tmp/git-2.16.2 make prefix=/usr/local install

  - name: delete source code
    become: yes
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /tmp/v2.16.2.tar.gz
      - /tmp/git-2.16.2
