---
- block:
  - name: set git_version
    set_fact:
      git_version: 2.16.2

  - name: remove earlier git
    becom: yes
    yum: name=git state=absent
    notify: remove earlier git

  - name: Dependency solution
    become: yes
    yum: name={{ git_depends }} state=latest

  - name: download source
    get_url:
      url: https://github.com/git/git/archive/v{{ git_version }}.tar.gz
      dest: /tmp

  - name: unarchive
    command: chdir=/tmp tar zxvf git-{{ git_version }}.tar.gz

  - name: make
    become: yes
    command: chdir=/tmp/git-{{ git_version }} make prefix=/usr/local all

  - name: install
    become: yes
    command: chdir=/tmp/git-{{ git_version }} make prefix=/usr/local install

  - name: delete source code
    become: yes
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/tmp/v{{ git_version }}.tar.gz"
      - "/tmp/git-{{ git_version }}"
    notify: git installed
