---
- block:
  - name: install packages from yum
    become: yes
    yum: name={{ item }} state=latest
    with_items:
      - "{{ packages }}"

  - name: install remi repo
    become: yes
    yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

  - name: install neovim
    block:
      - name: install neovim repo
        become: yes
        get_url:
          url: https://copr.fedorainfracloud.org/coprs/dperson/neovim/repo/epel-7/dperson-neovim-epel-7.repo
          dest: /etc/yum.repos.d/dperson-neovim-epel-7.repo

      - name: install neovim
        become: yes
        yum: name=neovim state=latest

  tags: packages

- block:
  - name: check php
    command: type php
    register: php_cmd
    ignore_errors: yes

  - include_tasks: php.yml hoge=hoge
    when: php_cmd|failed

  tags: php

- block:
  - name: check git
    stat: path=/usr/local/bin/git
    register: git

  - include_tasks: git.yml
    when: not git.stat.exists

  tags: git

- block:
  - name: check zsh
    shell: type zsh
    register: zsh
    ignore_errors: yes

  - include_tasks: zsh.yml
    when: zsh|failed

  tags: zsh

- block:
  - name: check tmux
    command: type tmux
    register: tmux_cmd
    ignore_errors: yes

  - include_tasks: tmux.yml
    when: tmux_cmd|failed
  tags: tmux

- block:
  - name: check docker
    command: type docker
    register: docker_cmd
    ignore_errors: yes

  - include_tasks: docker.yml
    when: docker_cmd|failed
  tags: docker
