---
- block:
  - name: Dependency resolution
    become: yes
    yum: name={{ tmux_depends }} state=latest

  - name: set tmux_path
    set_fact:
      tmux_path: /tmp/tmux-{{ tmux_version }}

  - name: download
    get_url:
      url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
      dest: /tmp

  - name: unarchive
    command: chdir=/tmp tar zxvf tmux-{{ tmux_version }}.tar.gz

  - name: configure
    command: chdir={{ tmux_path }} ./configure

  - name: make
    command: chdir={{ tmux_path }} make

  - name: make install
    become: yes
    command: chdir={{ tmux_path }} make install

  - name: clean /tmp
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ tmux_path }}"
      - "{{ tmux_path }}.tar.gz"
