---
- block:
  - name: "[zsh] Get src"
    git: repo=https://github.com/zsh-users/zsh.git
      dest=/tmp/zsh

  - name: "[zsh] Check config"
    stat: path=/tmp/zsh/configure
    register: zsh

  - name: "[zsh] Preconfig"
    command: chdir=/tmp/zsh ./Util/preconfig
    when: not zsh.stat.exists

  - name: "[zsh] Configure"
    shell: chdir=/tmp/zsh ./configure

  - name: "[zsh] Make"
    shell: chdir=/tmp/zsh make

  - name: "[zsh] Make install"
    become: yes
    shell: chdir=/tmp/zsh make install
    # Failed because build documents
    ignore_errors: yes
    notify: zsh installed

  - name: "[zsh] Clean"
    file:
      path: /tmp/zsh
      state: absent
