---
packages:
  - asciidoc
  - automake
  - autoconf
  - bzip2
  - bzip2-devel
  - curl-devel
  - docbook2X
  - expat-devel
  - gcc
  - gettext-devel
  - libevent-devel
  - libffi-devel
  - lua-devel
  - ncurses-devel
  - openssl-devel
  - perl-devel
  - perl-ExtUtils-MakeMaker
  - python-devel
  - readline-devel
  - ruby-devel
  - sqlite
  - sqlite-devel
  - tk-devel
  - xmlto
  - zlib-devel

epel_packages:
  - epel-release
  - neovim

php_version: 72

php:
  - php
  - php-cli
  - php-mbstring
  - php-pdo
  - php-gd
  - php-xml
  - php-mcrypt
