---
packages:
  - automake
  - autoconf
  - ncurses-devel
  - lua-devel
  - libevent-devel
  - python-devel
  - ruby-devel
  - zlib-devel
  - gcc
  - bzip2
  - bzip2-devel
  - readline-devel
  - sqlite
  - sqlite-devel
  - openssl-devel
  - tk-devel
  - libffi-devel

epel_packages:
  - epel-release
  - neovim

php_version: 72

php:
  - php
  - php-mbstring
  - php-pdo
  - php-gd
  - php-xml
  - php-mcrypt
