#!/bin/bash

clean() {
  e_newline
  e_header "Clean dotfiles..."

  for link in `find ~ -type l -maxdepth 1`;
  do
    unlink $link
    && e_success "$link"
  done

  e_newline && e_done "Clean dotfiles"
}

source $(cd $(dirname $0); pwd)/logging

clean
