## {{{ Template
#[[plugins]]
#repo = 
## }}}

## {{{ Options
# on_i = 1			: Load plugin when into insert mode.
# on_event = 'InsertCharPre'	: Load plugin when event run.
# on_ft = ['ft']		: Load plugin when ft is 'ft'.
# on_path = .*			: Load plugin when it is same buffer name.
# on_source = ['other plugin']	: Load plugin when 'other plugin' loaded.
# on_cmd = ['cmd']		: Load plugin when to run the 'cmd'.
# on_map = ['mapping']		: Mapping version of on_cmd.
# depends = ['depend plugin']	: If exist depens, load 'depend plugin' first.
# if
## }}}

## {{{ Hooks
##--------------------------------------------------------##
#   name           |  When run         | lazy off | lazy on#
#----------------------------------------------------------#
# hook_add         | When load plugin  |    OK    |   NG   #
# hook_source      | Before load plugin|    NG    |   OK   #
# hook_post_source | After load plugin |    NG    |   OK   #
# hook_post_updae  | When update plugin|    OK    |   OK   #
##--------------------------------------------------------##
## }}}

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # Switch ft according to the context of the cursor position
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # Detect ft according to the context of the cursor position
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'thinca/vim-splash'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'

[[plugins]]
repo = 'evanmiller/nginx-vim-syntax'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']
#repo = 'jelera/vim-javascript-syntax',{'autoload':{'filetypes':['javascript']}}

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'digitaltoad/vim-pug'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

[[plugins]]
repo = 'alvan/vim-php-manual'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]] # Syntax *.tpl
repo = 'vim-scripts/smarty-syntax'

# Toggle single line split to multi line / multi line join to single line
# gS / gJ 
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'
