# --------------------------------------------------------------------------#
# emmet
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'php', 'blade', 'ejs', 'jinja.html']
hook_add = '''
  " emmet expand <C-y> + ,
  let g:user_emmet_leader_key='<C-y>'
  let g:user_emmet_settings = {
        \'variables' : {
        \'lang' : 'ja'
        \},
        \}
'''

# --------------------------------------------------------------------------#
# html
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'gregsexton/MatchTag'
on_ft = ['html', 'blade', 'ejs']

# --------------------------------------------------------------------------#
# coloresque
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = ['html', 'css', 'less', 'sass', 'scss', 'stylus', 'vim', 'blade']

# --------------------------------------------------------------------------#
# Git
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'hotwatermorning/auto-git-diff'

# Javascript
# -----------
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

# typescript
# -----------
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# --------------------------------------------------------------------------#
# json
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']


# --------------------------------------------------------------------------#
# markdown
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# --------------------------------------------------------------------------#
# nginx
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['conf.nginx']
hook_add = '''
set tabstop=4
set softtabstop=4
set shiftwidth=4
let g:indent_guides_guide_size=4
'''

[[plugins]] # syntax for nginx files
repo = 'moskytw/nginx-contrib-vim'
on_ft = ['conf.nginx']

# --------------------------------------------------------------------------#
# PHP
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'flyinshadow/php_localvarcheck.vim'
on_ft = ['php']
hook_add = '''
  let g:php_localvarcheck_enable = 1
  let g:php_localvarcheck_global = 0
'''

# --------------------------------------------------------------------------#
# Python
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

# --------------------------------------------------------------------------#
# Smarty
# --------------------------------------------------------------------------#
[[plugins]] # Syntax *.tpl
repo = 'blueyed/smarty.vim'
on_ft = ['smarty']

# --------------------------------------------------------------------------#
# blade
# --------------------------------------------------------------------------#
repo = 'jwalton512/vim-blade'
on_ft = ['blade']

# --------------------------------------------------------------------------#
# ejs
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'nikvdp/ejs-syntax'
on_ft = ['ejs']

# --------------------------------------------------------------------------#
# toml
# --------------------------------------------------------------------------#
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = ['toml']

# --------------------------------------------------------------------------#
# Debug Client for PHP,Python,Perl,Ruby,etc,
# --------------------------------------------------------------------------#
[[plugins]]
repo = 'vim-vdebug/vdebug'
on_ft = ['php', 'python', 'perl', 'ruby']

# ansible
# -----------
[[plugins]]
repo='pearofducks/ansible-vim'
on_ft = ['yaml.ansible']

# --------------------------------------------------------------------------#
# nunjucks
# --------------------------------------------------------------------------#
[[plugins]]
repo='Glench/Vim-Jinja2-Syntax'
on_ft = ['njk']
