name: Sync labels
on:
  pull_request:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github/labels.yml

      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
